### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GamingMineblox** [arkhunter623/DBM-Music-System#1]

**Comment by GamingMineblox** [comment]
it gives me an error but nothing in the consol

**Comment by abolyderechte** [comment]
And I have this: https://prnt.sc/sfd1zo

**Comment by Waviestballoonx9** [comment]
I don't know how to set it up

**Comment by frutikys** [comment]
I just set it up, but I have no sound when bot playing the song. Do you know how to  fix it?
