### ISSUE TITLE
where tf do i put these commands? 

### ISSUE THREAD

**Issue by bodger666** [arkhunter623/DBM-Music-System#2]
your not realy helpfull whne coming to put these in so where do i put them?

**Comment by hawkmyg** [comment]
> your not realy helpfull whne coming to put these in so where do i put them?

you open the files with notepad then copy them into raw data on your command. 
Mind you this is out of date & the play doesn't work no more it needs fixed
https://gyazo.com/63d41355808b9a3bd3d3c014ffcae90a
https://gyazo.com/4c4784d81c06955a1bb95c3c20ac8c98
